//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5MinSetup.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StringTranslationGrid
    {
        public string Original_Text { get; set; }
        public string TextId { get; set; }
        public string mr { get; set; }
        public string hi { get; set; }
        public string fr { get; set; }
        public string zh { get; set; }
        public string es { get; set; }
    }
}
