//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5MinSetup.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StringTranslationDBEntities : DbContext
    {
        public StringTranslationDBEntities()
            : base("name=StringTranslationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Text> Texts { get; set; }
        public virtual DbSet<Translation> Translations { get; set; }
    
        public virtual ObjectResult<TranslationSP_Result> TranslationSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TranslationSP_Result>("TranslationSP");
        }
    }
}
