//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5MinSetup.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Text
    {
        public decimal Id { get; set; }
        public string TextId { get; set; }
        public string Text1 { get; set; }
        public Nullable<bool> System { get; set; }
    }
}
