CREATE DATABASE [StringTranslation]

CREATE TABLE [dbo].[Text](
	[Id] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[TextId] [varchar](500) NOT NULL,
	[System] [bit] NOT NULL,
 CONSTRAINT [PK_Text] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_TextId] UNIQUE NONCLUSTERED 
(
	[TextId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]




CREATE TABLE [dbo].[Languages](
	[Id] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[LanguageName] [nvarchar](max) NOT NULL,
	[LanguageCode] [char](2) NOT NULL,
 CONSTRAINT [PK_languages] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


CREATE TABLE [dbo].[TranslationArchive](
	[Id] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[TextId] [nvarchar](max) NOT NULL,
	[LanguageCode] [char](2) NOT NULL,
	[Translated_Text] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_TranslationArchive] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


CREATE TABLE [dbo].[TranslationLog](
	[Id] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[TextId] [nvarchar](max) NOT NULL,
	[LanguageCode] [char](2) NOT NULL,
	[Translated_Text] [nvarchar](max) NOT NULL,
	[System_Date] [datetime] NOT NULL,
 CONSTRAINT [PK_Translation_Log] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


CREATE TABLE [dbo].[TranslationMode](
	[Id] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[TextId] [varchar](500) NOT NULL,
	[LanguageCode] [char](2) NOT NULL,
	[Mode] [int] NOT NULL,
 CONSTRAINT [PK_TranslationMode] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[Translations](
	[Id] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[TextId] [varchar](500) NOT NULL,
	[LanguageCode] [char](2) NOT NULL,
	[Translated_Text] [nvarchar](max) NOT NULL,
	[OfficialBoolean] [bit] NOT NULL,
	[Votes] [int] NOT NULL,
 CONSTRAINT [PK_Translations] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


CREATE TABLE [dbo].[UserMaster](
	[Id] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[EmailId] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_UserMaster] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[Vote](
	[Id] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[Translation_Id] [numeric](18, 0) NOT NULL,
	[CookieID] [uniqueidentifier] NOT NULL,
	[IP] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Vote] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]