//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTranslator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public string Langugaes { get; set; }
        public string Translated_Text { get; set; }
        public string LanguageCode { get; set; }
        public string TextId { get; set; }
    }
}
