//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTranslator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public decimal Id { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
    }
}
