//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTranslator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public decimal Id { get; set; }
        public decimal Translation_Id { get; set; }
        public System.Guid CookieID { get; set; }
        public string IP { get; set; }
    }
}
